### ISSUE TITLE
Unresponsive 

### ISSUE THREAD

**Issue by hew** [dmitriiabramov/esfmt#32]
Doesn't appear to do anything on my machine (OSX, El Cap)  

![](http://f.cl.ly/items/0p0S2r30353E232d0r37/Screen%20Shot%202016-06-01%20at%201.25.26%20PM.png)

**Comment by dmitriiabramov** [comment]
oh.. wow. i didn't know anyone would try to use this package :)
It's still in 'work-in-progress' state, but you can stream input into `esfmt` command like this:
```
cat index.js | esfmt
```

and it will format it

**Comment by hew** [comment]
haha if you build it ... 

![](http://i.imgur.com/y1VQ9ve.png)

Thanks for the response. I will give it a shot.
